### ISSUE TITLE
Parallelogram Issue!

### ISSUE THREAD

**Issue by Uzayky** [Uzayky/git-github#4]
Hey guys, i have a litlle problem with my ''Paralelkenar.c'' work. After compile and run it , it respons like
                                     
                                                             *******
                                                              *******
                                                              *******
                                                              *******

If you have time for this litte work please help. Thanks all for help :)

**Comment by cagataycali** [comment]
It looks normal 
<img width="265" alt="screen shot 2017-10-03 at 00 02 01" src="https://user-images.githubusercontent.com/9213230/31099278-1e007abc-a7ce-11e7-920e-37c24fbfa4ba.png">

**Comment by cagataycali** [comment]
It have to be closed.
